### ISSUE TITLE
Support installation via composer

### ISSUE THREAD

**Issue by fago** [jmolivas/phpqa#21]
I'd like to add phpca to a project via `composer require jmolivas/phpqa=@dev --dev`

But that errors as phpca does not find its binaries, e.g.

> [Exception]  
>  bin/parallel-lint do not exist!

The binary exits in vendor/bin, also linking it to bin does not help.

**Comment by jmolivas** [comment]
@fago sorry for the delay got busy with other projects 

Starting on [v0.3.0](https://github.com/jmolivas/phpqa/releases/tag/0.3.0) you can install via composer using `composer require jmolivas/phpqa` I will test adding per project basis.

**Comment by jmolivas** [comment]
@fago I tested `composer require jmolivas/phpqa=@dev --dev` and it works now.

Fee free to re-open if any issues.
