### ISSUE TITLE
Update dependencies drupal/coder and squizlabs/php_codesniffer

### ISSUE THREAD

**Issue by naveenvalecha** [jmolivas/phpqa#30]
` - jmolivas/phpqa 0.4.0 requires squizlabs/php_codesniffer 2.5.1 -> satisfiable by squizlabs/php_codesniffer[2.5.1] but these conflict with your requirements or minimum-stability.`

Could we make it squizlabs/php_codesniffer >=2.5.1 <3.0

**Comment by naveenvalecha** [comment]
"squizlabs/php_codesniffer": "2.5.1"
Dependency only allowing drupal/coder to 8.2.3 to be installed not latest version

**Comment by jmolivas** [comment]
@naveenvalecha Updated with PR https://github.com/jmolivas/phpqa/pull/31 can you try `dev-master` and see if this fix your issue.

**Comment by naveenvalecha** [comment]
@jmolivas Thanks it worked for me. btw why are we are we requiring squizlabs/php_codesniffer in root composer.json can't we rely on drupal/coder ?

**Comment by jmolivas** [comment]
@naveenvalecha done `squizlabs/php_codesniffer` was removed, lets rely rely on `drupal/coder`.

**Comment by naveenvalecha** [comment]
@jmolivas Thank you!
