### ISSUE TITLE
Same project name, same purpose?

### ISSUE THREAD

**Issue by andygrunwald** [jmolivas/phpqa#35]
Hey Jesus, 

very cool project. Thank you.
I just want to drop a note that a project with the name `phpqa` is already out there.
Checkout https://github.com/EdgedesignCZ/phpqa

> Analyze PHP code with one command https://edgedesigncz.github.io/phpqa

I just want to let you know about this. Personally i dont mind, but this might raise confusion.

**Comment by jmolivas** [comment]
@andygrunwald After a quick search. I found several others thanks for letting me know.

At packagist
https://packagist.org/search/?q=phpqa

At github
https://github.com/search?o=desc&q=phpqa&s=&type=Repositories&utf8=%E2%9C%93

**Comment by andygrunwald** [comment]
For me it is fine to close this issue.
Now it is up to you if you change the name or just keep it :)

**Comment by mre** [comment]
Hey @jmolivas, we've added your project to [awesome-static-analysis](https://github.com/mre/awesome-static-analysis).
In case you want to rename the project, please let us know so we can update the link.

**Comment by jmolivas** [comment]
@andygrunwald I do not have any plans to rename it 

@mre thanks for adding it. I will let you know if name changes.

**Comment by andygrunwald** [comment]
@jmolivas Thats fine! Good luck with your project :)
