### ISSUE TITLE
Interactive Init

### ISSUE THREAD

**Issue by dshafik** [jmolivas/phpqa#6]
An interactive `phpqa init` would be great, asking to enable tools, and where their config files (or whatever makes sense config options) should be set to.

**Comment by jmolivas** [comment]
@dshafik: I did some changes PR is coming 
![phpqa-init](https://cloud.githubusercontent.com/assets/366275/8816979/5dfad362-2fe2-11e5-8ebb-ce11941d0375.png)

**Comment by jmolivas** [comment]
@dshafik: Done may try updating project and test it again.

**Comment by jmolivas** [comment]
I did another change, now you can pass a `--project` option to decide which project type to copy, based on  files at the project repo, at this point then only different one is the drupal configuration, this is an example how to use it:

![phpqa-init-project-current-drupal](https://cloud.githubusercontent.com/assets/366275/8820289/fa6fa044-3008-11e5-92e5-0a1555e6a1ea.png)
